### PR TITLE
Deprecate old instrumentation and REPL classes

### PR DESCRIPTION
**Pull request by mlvdv**
- @Deprecate all classes in the old instrumentation framework, along with tests, utilities
- @Deprecate the two REPL classes that don't belong in the Truffle API

### CODE REVIEW

**Comment by jtulach** [comment]
The gate checks are failing. Assigning back.

**Comment by mlvdv** [comment]
On my machine this PR builds, runs, and passes units tests cleanly with no complaints from Eclipse.  However I have not been able to get it past the gate.  Running the gate on my machine produces the same results as the Travis build.

The gate reports `Unnecessary @SuppressWarnings("rawtypes")` at lines 508 and 559 in the _old_ Instrumenter class:  `com.oracle.truffle.api.instrument.Instrumenter`

However, when those warnings are removed:
- Eclipse complains that they are needed and
- the gate reports that fully qualified references to `com.oracle.truffle.api.instrument.Instrumenter` "cannot be resolved to a type"

**Comment by woess** [comment]
what's the reason for fully qualifying all deprecated class names?

**Comment by mlvdv** [comment]
There appears to be no way to suppress warnings (-> gate errors) on imports of deprecated classes.

**Pull request merged**
