### PR TITLE
Adding check of javadoc broken links into travis pull request run

### PR DESCRIPTION
**Pull request by jtulach**
Run more tests to ensure documentation doesn't have broken links and missing tags.

### CODE REVIEW

**Comment by chumer** [comment]
I tried this before, but failed. Unfortunately mx javadoc requires to have "mx build" run before. In my opinion mx javadoc should just do the build automatically if not yet built. What do you think @gilles-duboscq ?

**Comment by chrisseaton** [comment]
Or you can have multiple commands as in `mx/mx build && mx/mx javadoc --unified`, or call a shell script with many commands in it.

**Comment by chumer** [comment]
`mx/mx build && mx/mx javadoc --unified` does not work on travis. don't know the reason. stopped investigating

**Comment by jtulach** [comment]
In the light of #15 this change is obsolete.

**Comment by gilles-duboscq** [comment]
Regarding javadoc: `mx javadoc` already does the build by default. What was the problem?

**Comment by smarr** [comment]
The build/gate did not fail when I introduced imperfect JavaDoc.

**Pull request closed without merging**
