### PR TITLE
Fix a possible overflow in the counting condition profile.

### PR DESCRIPTION
**Pull request by thomaswue**
Makes sure the sum of the counters of the true and false branch of a condition profile cannot overflow.

### CODE REVIEW

**Comment by thomaswue** [comment]
@mbrantner fyi.

**Comment by thomaswue** [comment]
@mbrantner fyi.

**Comment by mbrantner** [comment]
Great, thanks!

**Comment by chumer** [comment]
Looks good. Thanks for the fix.

**Pull request merged**
