### PR TITLE
Add capability to reload Source objects.

### PR DESCRIPTION
**Pull request by chumer**
I needed the capability to reload sources. Especially with url caching this can be hacky. So I introduced a new method reload in Source that keeps the original source unmodified but reloads the code from the URL or File.

### CODE REVIEW

**Comment by mlvdv** [comment]
What's the use case?

**Comment by woess** [comment]
Seems a bit strange to me. Wouldn't you rather want an uncached URL/File Source? You could then simply create a new one when you need it up-to-date.

**Comment by jtulach** [comment]
There was d9294237e1518b8fab5c7668945967bbbf0b2df5 and I got a feeling that Source is supposed to be immutable. That seems to be OK in this proposal, but the general motivation for the change is unclear.

**Comment by chumer** [comment]
I need the in R to auto reload source files on changes. There is no way to reload a source from with a given URL atm. Its always returning the same Source object which caches the code as field and never reloads its contents.

We would not need this change if URL source would not cache their instances globally. I am happy to remove the cache instead.

@mlvdv I think you introduced the URL source cache. Do you remember its rationale?

**Comment by mlvdv** [comment]
No, I'm not sure what the conversation was about that.  The original Source object wasn't much more than a collection of use cases in the different languages, since every language handled sources differently.

**Comment by woess** [comment]
I think we should remove the current (static!) cache from Source. Perhaps we could split it out into a separate API that builds on top of Source that languages can optionally use if they need caching (e.g. "SourceCache"), perhaps tied to a PolyglotEngine instance?

**Comment by jtulach** [comment]
OK. I prefer to remove the cache rather than trying to introduce an API for reload.

**Comment by jtulach** [comment]
How such change affects Source.equals then? Right now it assumes that if Source comes from the same File/URL it is the same one. That will no longer be true - the equals will have to be modified to really compare the content.

**Comment by chumer** [comment]
I don't think Source#equals should compare the code for File sources or URL sources as they are mutable. For literal sources it might be a good idea to compare the sources itself on equals.

**Comment by chumer** [comment]
Closing. Will open another one where I remove the caching capability.

**Comment by jtulach** [comment]
So what should Source#equals compare? Identity?

**Pull request closed without merging**
