### PR TITLE
Add explicit SCM metadata

### PR DESCRIPTION
**Pull request by gilles-duboscq**
This helps mx create valid pom files.

### CODE REVIEW

**Comment by woess** [comment]
LGTM

**Comment by chumer** [comment]
LGTM="Looks good to merge" ?

**Comment by woess** [comment]
LGTM=Looks Good To Me

**Comment by chumer** [comment]
3x improvement in terms of typed characters. impressive ;-)

**Comment by smarr** [comment]
If you want to go GitHub professional, you need this http://www.lgtm.in/ :wink:

**Pull request merged**
