### PR TITLE
CallTarget initialization must not throw NPE if PolyglotEngine is not initialized

### PR DESCRIPTION
**Pull request by woess**

### CODE REVIEW

**Comment by smarr** [comment]
Hm, this raises for me the general question, do we support execution outside of PolyglotEngine?

**Comment by woess** [comment]
That's a good question. In any case, it used to work so there was an incompatible API change in #1.

**Comment by ldaynes** [comment]
Not everyone would want their Truffle Engine to run though the polyglot engine API. So I would ward off any changes that make Truffle unusable outside of polyglot engine.

**Comment by jtulach** [comment]
Yes, Truffle execution without PolyglotEngine wrapper shall be supported. The fix is OK. Can we also have a test to make sure the fix never regresses?

**Comment by chumer** [comment]
We should remove the InstrumentatinMode from the graal truffle PE tests. That these tests will crash when running without wrapper is broken.

**Comment by jtulach** [comment]
The change falls into "documenting existing behaviour", so yes, we could integrate it. However the documentation is far from perfect. First of all I can't verify the code is compilable. Second, I believe the API classes in the code should hyperlinked.

**Comment by mlvdv** [comment]
This sounds like a platform policy decision (new to me) that code run outside PolyglotEngine is un-instrumentable (which also means un-debuggable, un-profileable, etc. etc.).  Has the strategic implication of this been discussed more widely?

**Comment by chumer** [comment]
Yes this has been discussed before. My latest policy update was the following: Yes the minimal Truffle example without instrumentation and polyglot engine, ie just using TruffleRuntime and CallTarget directly, must remain working and simple because Truffle is also used by non-dynamic-language use cases. All the nice instrumentation, debugging, polyglot engine stuff is allowed to not work for these use-cases.

**Comment by chumer** [comment]
Thanks for the change.

**Comment by jtulach** [comment]
Bugfixes in Truffle should be accompanied with a unit test, if it is possible to write one.

**Pull request merged**
