### PR TITLE
Adjustments to CHANGELOG.md

### PR DESCRIPTION
**Pull request by thomaswue**
Added skeleton for missing entries for versions 0.9, 0.10, and 0.11. Changed new format into two sections of "Summary" and "Migration Guide". Less level of details for long outdated versions.

### CODE REVIEW

**Comment by thomaswue** [comment]
Issue #42 is related.

**Comment by jtulach** [comment]
Please sync your branch and integrate.

**Comment by jtulach** [comment]
Action needed: "This branch has conflicts that must be resolved"

**Comment by jtulach** [comment]
Thanks. Time to click "Merge pull request". @thomaswue feel free to do it yourself or assign to me.

**Pull request merged**
