### PR TITLE
Make Message.WRITE final

### PR DESCRIPTION
**Pull request by eregon**
All `Message` statics are `final` except `WRITE`.

* The various `INSTANCE` fields are also not final, but accessed only here, should we make them `final` as well?

### CODE REVIEW

**Comment by woess** [comment]
@eregon yes, the `INSTANCE` fields should be final, too.

**Comment by eregon** [comment]
OK, will do.

**Comment by eregon** [comment]
Done.
`sigtest` data had to be adapted but I don't see any valid use case to set `Message.WRITE`, not to mention it's highly inconsistent. So I believe changing has no effect on real users.

**Comment by jtulach** [comment]
Changing WRITE field to final is correct, but incompatible change. I'd like to do it, but please get wider approval. Write to mailing list and to known language maintainers to confirm they are OK with the change. (Assuming they are) merge then.

**Comment by woess** [comment]
I approve of the change. It's an API error and _very_ unlikely somebody depends on it (nobody should ever write to the (WRITE) field), so it should be fixed.

**Comment by jtulach** [comment]
I'll merge this tomorrow.

**Comment by woess** [comment]
ready for merging, but needs to be rebased; @eregon

**Comment by eregon** [comment]
Rebased.

**Pull request merged**
